{% set PIO_PKG_NAME = 'toolchain-gccarmnoneeabi' %}
{% set PKG_NAME = 'platformio-' + PIO_PKG_NAME %}
{% set PKG_TYPE = 'package' %}
{% set VERSION = '1.60301.0' %}
{% set REPO = 'https://dl.bintray.com/platformio/dl-packages' %}
package:
  name: {{ PKG_NAME }}
  version: {{ VERSION }}

source:
  url: {{ REPO }}/{{ PIO_PKG_NAME }}-windows-{{ VERSION }}.tar.gz  # [win]
  url: {{ REPO }}/{{ PIO_PKG_NAME }}-linux_i686-{{ VERSION }}.tar.gz  # [linux32]
  url: {{ REPO }}/{{ PIO_PKG_NAME }}-linux_x86_64-{{ VERSION }}.tar.gz  # [linux64]
  url: {{ REPO }}/{{ PIO_PKG_NAME }}-darwin_x86_64-{{ VERSION }}.tar.gz  # [osx]

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script:
    python -c
      "import os.path; import os; import shutil;
      install_dir = os.path.join(os.environ['PREFIX'], 'share', 'platformio', '{{ PKG_TYPE }}s', '{{ PIO_PKG_NAME }}');
      shutil.copytree(os.environ['SRC_DIR'], install_dir);
      os.remove(os.path.join(install_dir, 'bld.bat'));  # [win]
      os.remove(os.path.join(install_dir, 'build.sh'));  # [not win]
      "

requirements:
  build:
    - python
